### ISSUE TITLE
Error when adding nextcloud calendar URL "Unknown RRULE property 'RRULE'"

### ISSUE THREAD

**Issue by pge** [iobroker-community-adapters/ioBroker.ical#184]
**Description**  
When adding a nextcloud Calendar URL no objects appear, but there is an error on the iobroker log file.

**To Reproduce**  
1. Install iCal Adapter
2. Add Nextcloud URL in scheme:
URL: https://<domain>/nextcloud/remote.php/dav/calendars/<user>/<calendar>/?export
User: <user>
Ignore SSL Error
3. No Joy

**Expected behavior**  
In theory, there should be appropriate data from my nextcloud calendars 

**Screenshots & Logfiles**  
```
2020-11-06 00:05:00.014  - ^[[32minfo^[[39m: host.iobroker instance system.adapter.ical.0 started with pid 11069
2020-11-06 00:05:01.040  - ^[[32minfo^[[39m: ical.0 (11069) starting. Version 1.7.4 in /opt/iobroker/node_modules/iobroker.ical, node: v12.19.0, js-controller: 3.1.6
2020-11-06 00:05:02.835  - ^[[32minfo^[[39m: mihome-vacuum.0 (1733) Disconnect
2020-11-06 00:05:03.253  - ^[[31merror^[[39m: ical.0 (11069) uncaught exception: Unknown RRULE property 'RRULE'
2020-11-06 00:05:03.254  - ^[[31merror^[[39m: ical.0 (11069) Error: Unknown RRULE property 'RRULE'
    at /opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:98:15
    at Array.forEach (<anonymous>)
    at parseRrule (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
    at parseLine (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
    at Array.map (<anonymous>)
    at Function.parseString (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
    at Function.RRule.fromString (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/rrule.ts:127:28)
    at Object.END (/opt/iobroker/node_modules/node-ical/ical.js:415:30)
    at Object.handleObject (/opt/iobroker/node_modules/node-ical/ical.js:452:39)
    at Object.parseLines (/opt/iobroker/node_modules/node-ical/ical.js:499:18)
2020-11-06 00:05:03.270  - ^[[32minfo^[[39m: ical.0 (11069) terminating
2020-11-06 00:05:03.270  - ^[[32minfo^[[39m: ical.0 (11069) Terminated (NO_ERROR): Without reason
2020-11-06 00:05:03.471  - ^[[31merror^[[39m: host.iobroker instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

**Versions:**  
```
/usr/bin/nodejs
--
  | v12.19.0
  | /usr/bin/node
  | v12.19.0
  | /usr/bin/npm
  | 6.14.8
  | nodejs:
  | Installiert:           12.19.0-deb-1nodesource1
  | Installationskandidat: 12.19.0-deb-1nodesource1
  | Versionstabelle:
  | *** 12.19.0-deb-1nodesource1 500
  | 500 https://deb.nodesource.com/node_12.x focal/main amd64 Packages
  | 100 /var/lib/dpkg/status
  | 10.19.0~dfsg-3ubuntu1 500
  | 500 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```

**Comment by jens-maus** [comment]
This seems to be related to https://github.com/jens-maus/node-ical/issues/14

Can you please provide an example ics file/export that exhibits this issue so that we can reproduce it accordingly? Thanks.

**Comment by pge** [comment]
Well, that's gonna be a tough one. 
This is my private calendar with personal information. 

Is there any hint to what RRULE Part of the appointments is the case so i can isolate it?

**Comment by jens-maus** [comment]
You can download it yourself and put it is a local file link into the iobroker.ical instance and then strip strings down until the issue disappears and then put back the part the issue appears and then anonymize it and send it in here.
