### ISSUE TITLE
ICAL Error - instance system.adapter.ical.2 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by svw2rene** [iobroker-community-adapters/ioBroker.ical#370]
The ICal Calender data no read anymore and no actual in states.
Restart of adapter will quitt with follow message in log:

instance system.adapter.ical.2 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Screenshots & Logfiles**  
instance system.adapter.ical.2 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Versions:**  
 - Adapter version: <ICal 1.11.6>
 - JS-Controller version: <js-controller-version: 4.0.9>
 - Node version: <node-version: v14.19.0>
 - Operating system: Debian Stretch

**Additional context**  
Debug exception from console

root@svw2-home-server:/opt/iobroker/node_modules/rrule# iobroker debug ical.2
Debugger listening on ws://127.0.0.1:9229/af270371-b938-4c7c-8661-01de342cf563
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module '/opt/iobroker/node_modules/rrule/dist/es5/rrule.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.ical/main.js:18:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/opt/iobroker/node_modules/rrule/package.json',
  requestPath: 'rrule'
}

**Comment by Apollon77** [comment]
Hm ... is the file existing that he mentions? 

Alternatve to debug (which is mainly there to really debug an adapter, simply change the loglevel of the instance and do a normal run
