### ISSUE TITLE
Exchange Kalender - ERROR when trying to convert to ISOString

### ISSUE THREAD

**Issue by matze-pe** [iobroker-community-adapters/ioBroker.ical#535]
Hallo,

seit 1 Woche hat sich die Kalenderanzeige "aufgehangen". Die .ics Datei ist abruf- und lesbar.
Im erweiterer Log des ICAL Adapters habe ich die nachfolgenden Fehler. In der Suche habe ich zum "ERROR when trying to convert to ISOString" ein Issue von 2021 gefunden, dieses wurde aber geschlossen. Da es keine Rückmeldung gab.

Anbei mein Log:

`ical.0
	2023-04-19 10:38:52.275	error	ERROR when trying to convert to ISOString

ical.0
	2023-04-19 10:38:52.275	error	Error: ERROR when trying to convert to ISOString at Object.END (/opt/iobroker/node_modules/node-ical/ical.js:587:21) at Object.handleObject (/opt/iobroker/node_modules/node-ical/ical.js:634:39) at Object.parseLines (/opt/iobroker/node_modules/node-ical/ical.js:686:18) at Immediate.<anonymous> (/opt/iobroker/node_modules/node-ical/ical.js:701:16) at processImmediate (node:internal/timers:466:21)

ical.0
	2023-04-19 10:38:52.275	error	uncaught exception: ERROR when trying to convert to ISOString

ical.0
	2023-04-19 10:30:15.343	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason`

Node.js = v16.19.1

edit: Node.js auf die empfolenen Version v18.16.0 aktualisiert. Fehler bleibt bestehen.

**Comment by mcm1957** [comment]
@matze-pe 
Please open a new issue if problem still exists with current releases.
