### ISSUE TITLE
RangeError: Invalid time zone specified

### ISSUE THREAD

**Issue by Jey-Cee** [iobroker-community-adapters/ioBroker.ical#625]
**Describe the bug**  
Since last update the error message appears in the log, see below.

**To Reproduce**  
No special steps needed.

**Expected behavior**  
No message in the log.

**Screenshots & Logfiles**  
`ical.0
	2023-12-20 19:00:01.386	info	starting. Version 1.13.5 in /opt/iobroker/node_modules/iobroker.ical, node: v18.17.1, js-controller: 5.0.17`

`Issue detected in RRule, event ignored; Please forward debug information to iobroker.ical developer: RangeError: Invalid time zone specified: undefined at Date.toLocaleString (<anonymous>) at t.rezonedDate (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/datewithzone.ts:42:17) at rezoneIfNeeded (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/iter/index.ts:152:47) at iter (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/iter/index.ts:78:33) at t._iter (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/rrule.ts:129:12) at t.between (/opt/iobroker/node_modules/rrule/dist/es5/webpack:/rrule/src/rrule.ts:194:21) at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:373:34) at processTicksAndRejections (node:internal/process/task_queues:95:5) RRule object: {"_cache":{"all":false,"before":[],"after":[],"between":[]},"origOptions":{"tzid":"undefined","dtstart":"2019-08-01T05:30:00.000Z","freq":2,"byweekday":[{"weekday":0},{"weekday":1},{"weekday":2},{"weekday":3}],"until":"2020-01-08T05:30:00.000Z"},"options":{"freq":2,"dtstart":"2019-08-01T05:30:00.000Z","interval":1,"wkst":0,"count":null,"until":"2020-01-08T05:30:00.000Z","tzid":"undefined","bysetpos":null,"bymonth":null,"bymonthday":[],"bynmonthday":[],"byyearday":null,"byweekno":null,"byweekday":[0,1,2,3],"bynweekday":null,"byhour":[5],"byminute":[30],"bysecond":[0],"byeaster":null}} now3: Tue Dec 19 2023 15:45:00 GMT+0100 (Mitteleuropäische Normalzeit) endpreview: Wed Dec 27 2023 19:00:02 GMT+0100 (Mitteleuropäische Normalzeit) string: DTSTART;TZID=undefined:20190801T053000 RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH;UNTIL=20200108T063000 options: {"tzid":"undefined","dtstart":"2019-08-01T05:30:00.000Z","freq":2,"byweekday":[{"weekday":0},{"weekday":1},{"weekday":2},{"weekday":3}],"until":"2020-01-08T05:30:00.000Z"}`

**Versions:**  
 - Adapter version: 1.13.5
 - JS-Controller version: 5.0.17
 - Node version: 18.17.1
 - Operating system: ubuntu server 22.04

**Additional context**  
NA

**Comment by Walkinlarge2010** [comment]
I have the same Problem, is there actual an soltion provided?
