### ISSUE TITLE
Error Cannot write file /UPLOAD_FILES_HERE.txt: ical.0 is not an object of type "meta"

### ISSUE THREAD

**Issue by mac89muc** [iobroker-community-adapters/ioBroker.ical#659]
Hello,
since two weeks my ical Adapter isn't working properly - the Log shows

`2024-04-10 10:37:04.930  - [34mdebug[39m: host.smarthome.local object change system.adapter.ical.0 (from: system.adapter.admin.0)
2024-04-10 10:37:04.930  - [32minfo[39m: host.smarthome.local stopInstance system.adapter.ical.0 (force=false, process=false)
2024-04-10 10:37:04.930  - [32minfo[39m: host.smarthome.local stopInstance canceled schedule system.adapter.ical.0
2024-04-10 10:37:07.971  - [34mdebug[39m: host.smarthome.local added notifications configuration of system.adapter.ical.0
2024-04-10 10:37:07.972  - [32minfo[39m: host.smarthome.local instance scheduled system.adapter.ical.0 0,25 3,10,19 * * *
2024-04-10 10:37:07.972  - [32minfo[39m: host.smarthome.local instance system.adapter.ical.0 started with pid 16152
2024-04-10 10:37:08.179  - [34mdebug[39m: ical.0 (16152) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-04-10 10:37:08.197  - [34mdebug[39m: ical.0 (16152) Objects client ready ... initialize now
2024-04-10 10:37:08.197  - [34mdebug[39m: ical.0 (16152) Objects create System PubSub Client
2024-04-10 10:37:08.197  - [34mdebug[39m: ical.0 (16152) Objects create User PubSub Client
2024-04-10 10:37:08.236  - [34mdebug[39m: ical.0 (16152) Objects client initialize lua scripts
2024-04-10 10:37:08.238  - [34mdebug[39m: ical.0 (16152) Objects connected to redis: 127.0.0.1:9001
2024-04-10 10:37:08.266  - [34mdebug[39m: ical.0 (16152) Redis States: Use Redis connection: 127.0.0.1:9000
2024-04-10 10:37:08.278  - [34mdebug[39m: ical.0 (16152) States create System PubSub Client
2024-04-10 10:37:08.279  - [34mdebug[39m: ical.0 (16152) States create User PubSub Client
2024-04-10 10:37:08.301  - [34mdebug[39m: ical.0 (16152) States connected to redis: 127.0.0.1:9000
2024-04-10 10:37:08.319  - [34mdebug[39m: ical.0 (16152) Plugin sentry Initialize Plugin (enabled=true)
2024-04-10 10:37:08.412  - [32minfo[39m: ical.0 (16152) starting. Version 1.14.2 in /usr/local/iobroker/node_modules/iobroker.ical, node: v18.19.0, js-controller: 5.0.19
2024-04-10 10:37:08.496  - [34mdebug[39m: ical.0 (16152) reading calendar from URL: https://calendar.google.com/calendar/ical/mycalendarurl2/basic.ics, color: #ff9300
2024-04-10 10:37:08.516  - [34mdebug[39m: ical.0 (16152) reading calendar from URL: http://p111-caldav.icloud.com/published/2/mycalendarurl, color: #178de8
2024-04-10 10:37:08.518  - [31merror[39m: ical.0 (16152) Cannot write file /UPLOAD_FILES_HERE.txt: ical.0 is not an object of type "meta"
2024-04-10 10:37:08.518  - [31merror[39m: ical.0 (16152) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-10 10:37:08.545  - [34mdebug[39m: host.smarthome.local Incoming Host message addNotification
2024-04-10 10:37:08.518  - [31merror[39m: ical.0 (16152) unhandled promise rejection: ical.0 is not an object of type "meta"
2024-04-10 10:37:08.545  - [31merror[39m: ical.0 (16152) Error: ical.0 is not an object of type "meta"
    at ObjectsInRedisClient.validateMetaObject (/usr/local/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:842:39)
    at ObjectsInRedisClient.writeFile (/usr/local/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:1139:13)
2024-04-10 10:37:08.545  - [31merror[39m: ical.0 (16152) ical.0 is not an object of type "meta"
2024-04-10 10:37:08.549  - [32minfo[39m: ical.0 (16152) terminating
2024-04-10 10:37:08.549  - [34mdebug[39m: ical.0 (16152) Plugin sentry destroyed
2024-04-10 10:37:08.549  - [33mwarn[39m: ical.0 (16152) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-04-10 10:37:08.861  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:08.885  - [34mdebug[39m: ical.0 (16152) Successfully cached content for calendar "https://calendar.google.com/calendar/ical/mycalendarurl2/basic.ics" as /usr/local/iobroker/node_modules/iobroker.ical/e35120f73f8e83fc03a8ee05d69a57e1
2024-04-10 10:37:08.942  - [34mdebug[39m: ical.0 (16152) Successfully cached content for calendar "http://p111-caldav.icloud.com/published/2/mycalendarurl" as /usr/local/iobroker/node_modules/iobroker.ical/3042a2550d77731367e1c2cc0af60200
2024-04-10 10:37:09.051  - [32minfo[39m: ical.0 (16152) terminating
2024-04-10 10:37:09.100  - [31merror[39m: host.smarthome.local instance system.adapter.ical.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-04-10 10:37:09.300  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:09.984  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:10.019  - [34mdebug[39m: host.smarthome.local object change system.adapter.ical.0 (from: system.adapter.admin.0)
2024-04-10 10:37:10.019  - [32minfo[39m: host.smarthome.local "system.adapter.ical.0" disabled
2024-04-10 10:37:10.019  - [32minfo[39m: host.smarthome.local stopInstance system.adapter.ical.0 (force=false, process=false)
2024-04-10 10:37:10.019  - [32minfo[39m: host.smarthome.local stopInstance canceled schedule system.adapter.ical.0
2024-04-10 10:37:10.776  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:20.630  - [34mdebug[39m: host.smarthome.local object change system.adapter.ical.0 (from: system.adapter.admin.0)
2024-04-10 10:37:20.630  - [32minfo[39m: host.smarthome.local stopInstance system.adapter.ical.0 (force=false, process=false)
2024-04-10 10:37:20.630  - [34mdebug[39m: host.smarthome.local stopInstance system.adapter.ical.0 not scheduled
2024-04-10 10:37:30.916  - [34mdebug[39m: host.smarthome.local object change system.adapter.ical.0 (from: system.adapter.admin.0)
2024-04-10 10:37:30.917  - [32minfo[39m: host.smarthome.local "system.adapter.ical.0" enabled
2024-04-10 10:37:30.917  - [32minfo[39m: host.smarthome.local stopInstance system.adapter.ical.0 (force=false, process=false)
2024-04-10 10:37:30.917  - [34mdebug[39m: host.smarthome.local stopInstance system.adapter.ical.0 not scheduled
2024-04-10 10:37:33.995  - [34mdebug[39m: host.smarthome.local added notifications configuration of system.adapter.ical.0
2024-04-10 10:37:33.997  - [32minfo[39m: host.smarthome.local instance scheduled system.adapter.ical.0 0,25 3,10,19 * * *
2024-04-10 10:37:33.997  - [32minfo[39m: host.smarthome.local instance system.adapter.ical.0 started with pid 17392
2024-04-10 10:37:34.206  - [34mdebug[39m: ical.0 (17392) Redis Objects: Use Redis connection: 127.0.0.1:9001
2024-04-10 10:37:34.225  - [34mdebug[39m: ical.0 (17392) Objects client ready ... initialize now
2024-04-10 10:37:34.225  - [34mdebug[39m: ical.0 (17392) Objects create System PubSub Client
2024-04-10 10:37:34.226  - [34mdebug[39m: ical.0 (17392) Objects create User PubSub Client
2024-04-10 10:37:34.267  - [34mdebug[39m: ical.0 (17392) Objects client initialize lua scripts
2024-04-10 10:37:34.270  - [34mdebug[39m: ical.0 (17392) Objects connected to redis: 127.0.0.1:9001
2024-04-10 10:37:34.292  - [34mdebug[39m: ical.0 (17392) Redis States: Use Redis connection: 127.0.0.1:9000
2024-04-10 10:37:34.305  - [34mdebug[39m: ical.0 (17392) States create System PubSub Client
2024-04-10 10:37:34.305  - [34mdebug[39m: ical.0 (17392) States create User PubSub Client
2024-04-10 10:37:34.327  - [34mdebug[39m: ical.0 (17392) States connected to redis: 127.0.0.1:9000
2024-04-10 10:37:34.343  - [34mdebug[39m: ical.0 (17392) Plugin sentry Initialize Plugin (enabled=true)
2024-04-10 10:37:34.428  - [32minfo[39m: ical.0 (17392) starting. Version 1.14.2 in /usr/local/iobroker/node_modules/iobroker.ical, node: v18.19.0, js-controller: 5.0.19
2024-04-10 10:37:34.495  - [34mdebug[39m: ical.0 (17392) reading calendar from URL: https://calendar.google.com/calendar/ical/mycalendarurl2/basic.ics, color: #ff9300
2024-04-10 10:37:34.518  - [34mdebug[39m: ical.0 (17392) reading calendar from URL: http://p111-caldav.icloud.com/published/2/mycalendarurl, color: #178de8
2024-04-10 10:37:34.520  - [31merror[39m: ical.0 (17392) Cannot write file /UPLOAD_FILES_HERE.txt: ical.0 is not an object of type "meta"
2024-04-10 10:37:34.520  - [31merror[39m: ical.0 (17392) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-04-10 10:37:34.546  - [34mdebug[39m: host.smarthome.local Incoming Host message addNotification
2024-04-10 10:37:34.520  - [31merror[39m: ical.0 (17392) unhandled promise rejection: ical.0 is not an object of type "meta"
2024-04-10 10:37:34.546  - [31merror[39m: ical.0 (17392) Error: ical.0 is not an object of type "meta"
    at ObjectsInRedisClient.validateMetaObject (/usr/local/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:842:39)
    at ObjectsInRedisClient.writeFile (/usr/local/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:1139:13)
2024-04-10 10:37:34.546  - [31merror[39m: ical.0 (17392) ical.0 is not an object of type "meta"
2024-04-10 10:37:34.550  - [32minfo[39m: ical.0 (17392) terminating
2024-04-10 10:37:34.550  - [34mdebug[39m: ical.0 (17392) Plugin sentry destroyed
2024-04-10 10:37:34.550  - [33mwarn[39m: ical.0 (17392) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-04-10 10:37:34.787  - [34mdebug[39m: ical.0 (17392) Successfully cached content for calendar "http://p111-caldav.icloud.com/published/2/mycalendarurl" as /usr/local/iobroker/node_modules/iobroker.ical/3042a2550d77731367e1c2cc0af60200
2024-04-10 10:37:34.793  - [34mdebug[39m: ical.0 (17392) Successfully cached content for calendar "https://calendar.google.com/calendar/ical/mycalendarurl2/basic.ics" as /usr/local/iobroker/node_modules/iobroker.ical/e35120f73f8e83fc03a8ee05d69a57e1
2024-04-10 10:37:34.875  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:34.900  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:35.053  - [32minfo[39m: ical.0 (17392) terminating
2024-04-10 10:37:35.058  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications
2024-04-10 10:37:35.098  - [31merror[39m: host.smarthome.local instance system.adapter.ical.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-04-10 10:37:36.538  - [34mdebug[39m: host.smarthome.local Incoming Host message getNotifications`

Thanks in advance for your support.

Node-js 18.19.0
NPM 10.2.3
js-controller 5.0.19
tried with ical 1.14.3 & 1.14.2 - same error
os macOS 14.4.1 Sonoma on Mac mini M2

**Comment by klein0r** [comment]
That's strange. The meta object should be created automatically:

https://github.com/iobroker-community-adapters/ioBroker.ical/blob/4b5ec8fc753fd5a88adf479f3fcc445c3aaa2030/io-package.json#L216-L237

Can you check if the object doesn't exist in the object tab?

**Comment by mac89muc** [comment]
@klein0r 

Looks similar in /usr/local/iobroker/node_modules/iobroker.ical/io-package.json


_________________________________
"instanceObjects": [
{
"_id": "",
"type": "meta",
"common": {
"name": {
"en": "Meta storage for user files",
"de": "Meta-Speicher für Benutzerdateien",
"ru": "Meta Storage для файлов пользователей",
"pt": "Meta de armazenamento para arquivos de usuário",
"nl": "Meta opslag voor gebruikersbestanden",
"fr": "Stockage Meta pour les fichiers utilisateur",
"it": "Meta storage per i file utente",
"es": "Meta almacenamiento para archivos de usuario",
"pl": "Meta storage for user files",
"uk": "Зберігання мета для файлів користувачів",
"zh-cn": "用户档案的储存"
},
"type": "meta.user"
},
"native": {}
},
___________________________________

maybe something to do with my iob macOS installation - not the usual linux ???
Or do you mean under the objects tab in the iob webinterface?

![image](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/69312437/7427e0a2-a10f-4570-bce1-4c9a2d6fde90)

**Comment by klein0r** [comment]
> Or do you mean under the objects tab in the iob webinterface?

I mean the real existing object in the database. And it looks like that's not existent in your installation.
Can you share the instance object `system.adapter.ical.0` (or check if the meta attribute is defined there)?

**Comment by mac89muc** [comment]
seems it's missing...
something to do with macOS?

![image](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/69312437/f1b2eb58-db6e-4d8f-b8ca-d6d35da8efde)

**Comment by klein0r** [comment]
> seems it's missing...

The screenshot shows the instance object in the second line. Just open it and check the `instanceObjects`.

**Comment by mac89muc** [comment]
in the mentioned second line there's no "type": "meta.user"

![image](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/69312437/2873ff8e-0208-45f2-bb40-b20065cb9934)

but  in the first line (system.adapter.ical) it exists

![image](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/69312437/41c3b6ce-b224-4315-a0bb-f2843b473240)

**Comment by klein0r** [comment]
That's strange. Please upload the adapter again (via adapters tab or `iobroker upload ical`).
Does that work without any errors? Please share the output

**Comment by mac89muc** [comment]
@klein0r  👍🏻 seems to work properly now - no log errors.

Danke für den schnellen Support
Gruß

**Comment by klein0r** [comment]
> seems to work properly now

The big question is, why the automatic upload (which is executed after every adapter update) wasn't working
